project: 
  type: website
  
website: 
  title: "SONA Research" 
  site-url: "https://ritpsych.github.io/sona/" 
  repo-url: https://github.com/RITpsych/sona
  
  page-footer:
    right: "This page is built with Coffee and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Dustin Haraden, 2024"
  
  navbar:
    background: "#b55609"  #https://quarto.org/docs/websites/website-navigation.html
    search: true
    left:
      - href: index.qmd
        text: Welcome
      - href: labs/index.qmd
        text: Labs
      - href: https://rit.sona-systems.com/
        text: Link to SONA
      - page1.qmd
      - page2.qmd


format:
  html:
    theme:
      light: flatly 
      dark: darkly
    code-copy: true
    code-overflow: wrap


filters:
  - include-files.lua
  - quarto

  
