project: 
  type: website
  
website: 
  page-navigation: true
  title: "RIT Psychology" 
  site-url: "https://ritpsych.github.io/sona/" 
  repo-url: https://github.com/RITpsych/sona
  
  page-footer:
    right: "This page is built with Coffee and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Dustin Haraden, 2024"
  
  sidebar:
    background: "#D9E3E4"
    logo: "images/hex-PSYC_640.png"
    pinned: true
    align: center
        

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - href: labs/index.qmd
        text: Labs
      - page1.qmd
      - page2.qmd


format:
  html:
    theme:
      light: journal # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: journal
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
