project: 
  type: website
  
website: 
  title: "RIT Psychology" 
  site-url: "https://ritpsych.github.io/sona/" 
  repo-url: https://github.com/RITpsych/sona
  
  page-footer:
    right: "This page is built with Coffee and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Dustin Haraden, 2024"
  
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Welcome
      - href: labs/index.qmd
        text: Labs
      - page1.qmd
      - page2.qmd


format:
  html:
    theme:
      light: flatly 
      dark: darkly
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap


filters:
  - include-files.lua
  - quarto

  
