---
title: "Welcome!"
subtitle: "Everything SONA Related"
---

**SONA Coordinator**: Dustin Haraden, PhD

The content from this site has been previously created by Dr. Alan Smerbeck, and will be updated periodically. For any questions, please reach out to the current SONA Coordinator (sona\@rit.edu)

# Overview

Psychology is a science that relies on data and experimentation. Research determines which theories are well-supported and which should be discarded. Understanding psychology research is important to understanding psychology, which is why all PSYC 101 classes have the research experience requirement.

SONA Systems is the system that we use at RIT (as do many other universities) to organize all research looking for student participation. This is a central location for you to identify the available studies, participate in them, receive course credit (and some studies may even offer payment).

Please use this website to navigate through the SONA system as either a student participant, researcher or instructor. Reach out to the SONA coordinator if you have any questions (sona\@rit.edu).

# Getting Started

-   Sections based on your role

# Participant Info

This requirement is pass/fail. If you have 8 credits of research experience by 5pm on the last day of classes, you pass. If you have fewer than 8 credits at that time, your course grade will be marked down the equivalent of one ‘step’ in the plus / minus system (i.e., B+ to B; B- to C+; D to F). This is managed through a system called SONA, which is why participation credits are often called SONA credits. 1 SONA credit is assigned per 15 minutes of participation, so 8 credits require a total of 2 hours’ time.

Face-to-face studies in which you come in to the lab to do a task require a little more effort than completing surveys on your computer, and they also give you more insight into psychological research. As such, face-to-face studies offer a bonus SONA credit on top of the regular rate. So, a 30-minute online study would award 2 credits, while a 30-minute face-to-face study would award 3. You can tell which ones are face-to-face because they don’t say Online Study in the description.

You can earn credits in two ways: You can participate in real research studies OR you can complete research alternatives. You can identify research alternatives because they say Research Alternative next to them in the SONA listing. Research alternatives simulate real studies but do not collect data for analysis. If you can participate in real research, you are encouraged to do so, but participation is voluntary. Research alternatives are provided for students who cannot or choose not to participate in research.

If you are under 18, you cannot participate in most research studies because you cannot consent for yourself. You can complete research alternatives without parental consent. However, research alternatives are not available to all students until the last two weeks of class. Minor students (those aged 17 or under) can follow a special procedure to have early access to research alternatives, detailed [HERE](https://ritpsych.github.io/sona/student.html#research-alternatives-for-minors). This procedure is not required; minor students can still wait until the last two weeks of the semester to complete research alternatives.

Whether you complete real research or alternatives, you must sign up through http://rit.sona-systems.com to get credit.
