---
title: Lectures
execute:
  freeze: true
---

# Schedule

Slides for the course will be posted here prior to the lecture in which they occur. I will do my best to keep on top of them and I would like to have them be in both a PDF and HTML format so that it is easy to access for everyone.

| Week   | Date  | Topic                                  | Slides                                                                                                                                                                                                                                                                                                                                                    |
|---------|---------|:--------|:-------------------------------|
| 1      | 09/27 | Introduction and overview              | LSR Ch 1 & 3                                                                                                                                                                                                                                                                                                                                              |
| \-     | 09/29 | Research methods                       | LSR CH 2 & 4, [Rothman et al. (2013)](readings/Rothman_2013.pdf)[^1]                                                                                                                                                                                                                                                                                      |
| \-     | 09/30 | *Lab: Introduction to R*               |                                                                                                                                                                                                                                                                                                                                                           |
| 2      | 10/04 | Latent variables and psychometrics     | Podcast: [Quantitude, S2E21 -- Yes, Virginia... There ARE Latent Variables](https://quantitudepod.org/listen/) (Make sure you scroll down to the correct episode) [CC available here](https://uoregon.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=9e5c5f9e-666b-4741-875b-adba015e9ded)., [Bringmann et al., 2022,](readings/bringmann_etal_2022.pdf) |
| \-     | 10/06 | Describing data                        | LSR Ch 5 & 6                                                                                                                                                                                                                                                                                                                                              |
| \-     | 10/07 | *Lab: R basics and descriptives*       |                                                                                                                                                                                                                                                                                                                                                           |
| 3      | 10/11 | Describing data                        | [Ozer & Funder (2019)](readings/Ozer_Funder_2019.pdf)                                                                                                                                                                                                                                                                                                     |
| \-     | 10/13 | Probability                            | LSR Intro to Part IV and Ch 9.1-9.3, [Wetzels et al. (2011)](readings/Wetzels_etal_2011.pdf)                                                                                                                                                                                                                                                              |
| \-     | 10/14 | *Lab: Functional programming*          |                                                                                                                                                                                                                                                                                                                                                           |
| 4      | 10/18 | Probability                            | LSR Ch 9.4                                                                                                                                                                                                                                                                                                                                                |
| \-     | 10/20 | Probability                            | LSR Ch 9.5-9.6                                                                                                                                                                                                                                                                                                                                            |
| \-     | 10/21 | *Lab: Probability distributions*       |                                                                                                                                                                                                                                                                                                                                                           |
| 5      | 10/25 | Sampling                               | LSR Ch 10                                                                                                                                                                                                                                                                                                                                                 |
| \-     | 10/27 | Hypothesis testing                     | LSR Ch 11                                                                                                                                                                                                                                                                                                                                                 |
| \-     | 10/28 | *Lab: Data wrangling*                  |                                                                                                                                                                                                                                                                                                                                                           |
| 6      | 11/01 | Hypothesis testing                     | [Sainani (2012)](readings/Sainani_2012.pdf)                                                                                                                                                                                                                                                                                                               |
| \-     | 11/03 | Hypothesis testing                     |                                                                                                                                                                                                                                                                                                                                                           |
| \-     | 11/04 | *Lab: Graphing with ggplot2*           |                                                                                                                                                                                                                                                                                                                                                           |
| 7      | 11/08 | Critiques of hypothesis testing        | [Simmons et al. (2011)](readings/Simmons_etal_2011.pdf) [Cumming (2014)](readings/Cumming_2014.pdf)                                                                                                                                                                                                                                                       |
| \-     | 11/10 | Open Science and Wrap-up               | [Five Thirty Eight](https://fivethirtyeight.com/features/science-isnt-broken/)                                                                                                                                                                                                                                                                            |
| \-     | 11/11 | *Lab: No Lab*                          |                                                                                                                                                                                                                                                                                                                                                           |
| 8      | 11/15 | One-sample tests                       | LSR Ch 13.1-13.2                                                                                                                                                                                                                                                                                                                                          |
| \-     | 11/17 | Comparing two means (paired)           | LSR Ch 13.3-13.11                                                                                                                                                                                                                                                                                                                                         |
| \-     | 11/18 | *Lab: One- and paired-samples t-tests* |                                                                                                                                                                                                                                                                                                                                                           |
| 9      | 11/22 | Something different: RMarkdown         |                                                                                                                                                                                                                                                                                                                                                           |
| \-     | 11/24 | **Thanksgiving**                       |                                                                                                                                                                                                                                                                                                                                                           |
| \-     | 11/25 | *Lab: No Lab*                          |                                                                                                                                                                                                                                                                                                                                                           |
| 10     | 11/29 | Comparing two means (independent)      |                                                                                                                                                                                                                                                                                                                                                           |
| \-     | 12/01 | Effect sizes and assumptions           |                                                                                                                                                                                                                                                                                                                                                           |
| \-     | 12/02 | *Lab: Independent samples t-tests*     |                                                                                                                                                                                                                                                                                                                                                           |
| Finals | 12/05 |                                        |                                                                                                                                                                                                                                                                                                                                                           |
| \-     | 12/07 |                                        |                                                                                                                                                                                                                                                                                                                                                           |

[^1]: There are several great commentaries on this article that I would encourage you to read. They are: - [Richiardi et al. (2013).](readings/Richiardi_2013.pdf) Representativeness is usually not necessary and often should be avoided. - [Nohr et al. (2013).](readings/Nohr_2013.pdf) Epidemiologists have debated representativeness for more than 40 years---has the time come to move on? - [Elwood (2013).](readings/Elwood_2013.pdf) On representativeness - [Ebrahim et al. (2013).](readings/Ebrahim_2013.pdf) Should we always deliberately be non-representative?
