---
title: Student
execute:
  freeze: true
---

This section is designed to answer any questions that you may have as a participant. Below you can find the sections and navigate to them based on your current status. If you have questions or problems that are not addressed here, please reach out to the SONA Coordinator ([sona\@rit.edu](mailto:sona@rit.edu)).

## First Time Users

This section is for folks who have [***never***]{.underline} used SONA before. You may be taking PSYC 101 and need to complete the expected 8 credits, or you might be in a PSYC class that offers some extra credit. Whatever it is, if this is your first time hearing about SONA, you are in the right place.

### Creating a new SONA account

-   [**Create a New Account**]{.underline}

    At the bottom of the RIT SONA website, there is a button that says "Request Account". Click that to start the process of creating your account.

    Or you could [just click this link here](http://rit.sona-systems.com/student_new_user.aspx){target="_blank"} to go right to the page

> **NOTE:** Your User ID is what is before the @rit.edu (e.g., Email: abc1234\@rit.edu; User ID: abc1234).

\[INSERT PICTURE OF THE CLASS SELECTION SECTION\]

**Select only the class or classes you are enrolled in.** Check to make sure you have the right section - look at the section number (i.e., PSYC 101-04), the 5-digit course code, and when/how the class meets. If you enroll yourself in the wrong class, you might not get credits that you have earned. Do NOT enroll yourself in every class or in any class that you aren't in.

-   Log in to your new account!

    You will receive an email with a temporary password, please update this...or don't. We aren't your boss.

    -   Upon logging in, you will complete a short survey to see what studies work best for you. **ANSWER THESE ACCURATELY**. If you report inaccurate information here, you can lose all your credits and

Once you create an account, you'll be asked to acknowledge the human subjects policy. Then, you will be directed to complete a 5-question prescreen that asks about your age, vision, and hearing. Be sure to provide accurate information. If you tell the prescreen that you are under 18 when you are 18+ or vice versa, you will lose all of your credits and be prohibited from earning more credits for the rest of the semester.

# Signing up for Studies

To sign up for studies, click on Studies or View Available Studies. This shows you all the studies currently registered in the system. If the leftmost column says Timeslots Available, they are currently accepting new participants.

Check the eligibility criteria on the rightmost column. Studies that do not match your screening criteria will be omitted, but there are other eligibility criteria not included in the screening, so be sure to check. If you’re eligible, click on the study to sign up. You can do online studies immediately. For face-to-face studies, you’ll be prompted to schedule a time to come into the lab (usually in Eastman). Under Study Information, the Credits line will tell you how many credits you can earn by completing the full study.

Studies begin with a consent form. Read it carefully and decide whether to consent. Research alternatives begin with a disclosure of what is involved in the task, but do not require you to officially consent.

Be honest. Do not lie about your personal characteristics to pretend you are eligible for a study or provide false information when completing a questionnaire. Study data is being used for real research and inaccurate responses hold back science. If you’re asked a question you feel uncomfortable providing a truthful answer to, in some cases you can skip that question, and in all cases, you are free to quit the study.

Pay attention! You can lose your credits if you responded randomly or without effort. If your responses show you were not reading and thinking, the researchers can take away automatic credit when they review your data. Studies will notify you if you have been denied credit for failing attention checks. If this happens to you, find a new study and pay closer attention.

You can quit any study or research alternative at any time. You usually will not receive partial credit for the time you spent on the study. If partial credit is available, that will be explained in that study’s consent.

Research and research alternatives have a debriefing form at the end which explains the purpose of the study. This gives you a chance to learn more about research and to ask any questions.

Make sure you go all the way to the end of the study. The last page, for example, might ask you to click a link or button to finish up. This is necessary to assign you credit.

Read any post-study instructions carefully. For example, some allow you to choose between entering a raffle and getting SONA credit. For online studies, make sure you click through to the end of the study to ensure credit.

Most online studies assign credit automatically in which case you should receive credit within a few minutes. Some online studies assign credit manually, as do all face-to-face studies. In this case, it can take up to 1 week for your credit to be posted. If you haven’t been credited by that time, contact the researcher. You don’t need to notify your professor about your credits. They will be handled automatically.

Many studies don’t begin until about 3-4 weeks into the semester, so don’t worry if there aren’t many available right away. Studies are added and removed throughout the semester, so check back often. If you want to do real studies for your research requirement, don’t wait until the last minute! Many studies close or fill up before the end of the semester.

Don't worry if you're not eligible for some of the posted studies. There will be enough studies and research alternatives available to meet your class requirements.

Most research alternatives are not made available until the last 2 weeks of the semester, but some may be posted earlier; check back occasionally to see what’s available. You can identify research alternatives because they have the words Research Alternative in the title and the description. Sufficient research alternatives will be made available to ensure that students who are ineligible for or choose not to participate in real research will be able to earn all required credits.

## Research Alternatives for Minors 

Minor students (those under the age of 18) cannot consent to research and so are restricted to completing research alternatives, which are typically only available the last two weeks of the semester. Some minor students have expressed a desire to begin completing research alternatives earlier. This option was created with their preferences in mind. 

 If you will be a minor, age 17 or under, on the last day of the Add/Drop period for the current semester, you can gain early access to the research alternatives. You must follow the steps listed below. 

** Note: If any adult student (age ≥18 on the last day of this semester’s Add/Drop period) gains or attempts to gain early access to the research alternatives, any earned SONA credits will be revoked and that student will be prohibited from earning SONA credit through any means until the end of the semester. There may be other penalties as well.** 

Steps:

 1. Send an email to your PSYC101 instructor and the SONA director (sona@rit.edu) indicating that you plan to access the research alternatives early. The subject line should be “PSYC101 Under 18 Access Request”. The email MUST include the following information: 

- Your full name
- Your RIT username (which will be your SONA username)
- Your student ID number
- Your age and date of birth
- Your PSYC101 instructor name, section number (01, 02, etc.) and 5-digit course code (e.g. 14288)
- A photograph of an official ID which lists your name and date of birth – driver’s license, passport, etc.

 Any student who proceeds to Step 2 without ALL of this information emailed to your instructor and the SONA director may incur the same penalties listed for adult students in the Note above. 

2. You do not need to wait for confirmation; the email is for record-keeping purposes. Once that email is sent, you can get a SONA account. Follow general account directions, but when you are asked to pick which class you are a part of, select BOTH your PSYC101 section (be sure to get the right one – check for the instructor’s name and the exact section) AND the section labeled “PSYC101 Under 18”. Do not select any other courses.

3. You will now be able to sign up for Research Alternatives. You should not sign up for any other studies – you’re not eligible. Once you’re awarded credit for participation, you will be asked where to direct that credit. Select your PSYC101 section. 

**If this seems overly complicated, remember that you’re free to wait until the last two weeks of the semester, when the research alternatives will be open to everyone, at which point you can access the research alternatives while enrolled only in your PSYC 101 class.**
